stages:
  data_ingestion:
    cmd: python src\pipeline\stage_01_data_ingestion.py
    deps:
      - src\pipeline\stage_01_data_ingestion.py
      - src\constants\__init__.py
    outs:
      - artifacts\DataIngestion\images
      - artifacts\DataIngestion\RSNA.zip

  data_validation:
    cmd: python src\pipeline\stage_02_data_validation.py
    deps:
      - src\pipeline\stage_02_data_validation.py
      - src\constants\__init__.py

  model_training:
    cmd: python src\pipeline\stage_03_training_evaluation.py
    deps:
      - src\pipeline\stage_03_training_evaluation.py
      - artifacts\DataIngestion\images
      - src\constants\__init__.py
      - src\model\model.py
    outs:
      - artifacts\ModelTrainings\model.keras
